set-up  portofolio
SabaAhmad786/mobile-versio pull request #1
Opened 2022-09-22 13:37 UTC by SabaAhmad786

This is a set-up mobile portfolio website project. In this project, I worked on
1) setting up the linters
2) added Html and CSS files
3) and .gitignore files
kindly review my project

2022-09-22 14:04 UTC, Nyame-Wolf requested changes
# STATUS: REQUIRED CHANGES :recycle: 

Hi @SabaAhmad786  :wave: 

Your project page is looking fantastic so far :star_struck: ! 

However, there is still some room for improvement, that can help you have better code and make your project professional :sunglasses: 

![](https://media.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif)

## Highlights :sparkles:

- Great work using the right GitHub Flow :100: 
- Great work using the same font as Figma design ☑️ 
- Commits are descriptive and meaningful :+1: 
- Project Documentation (PR, README) is professional :necktie: 

Congrats on your work so far! :clap:  

## Required Changes ♻️

There are some issues that you still need to work on to go to the next project, but you are almost there! 
_For more information, check the comments under the review :arrow_down:_

## Optional suggestions :ballot_box_with_check: 

_Every comment with the **[OPTIONAL]** prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can improve the quality of your code :100:_

Happy coding and keep it up! :raised_hands: 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
  Please, remember to tag me **@Nyame-Wolf**  in your question so I can receive the notification.

  **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------

  _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)

2022-09-22 14:04 UTC, Nyame-Wolf commented on README.md
> +This project is [MIT](./MIT.md) licensed.
[OPTIONAL] Kindly add the licence file MIT.md file here. This currently opens an empty page. The way to do this is described [here](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository) 
-At the bottom of the readme template you used as well.

2022-09-22 14:04 UTC, Nyame-Wolf commented on README.md
> +Feel free to check the [issues page](../../issues/).
[OPTIONAL] Kindly add the correct link to the issues page that point to your project.
<img width="1075" alt="Screenshot 2022-09-22 at 03 23 50" src="https://user-images.githubusercontent.com/48546992/191764205-c6b66216-5ad3-4bdf-8f61-fef2671e6751.png">
Its always good practice to do this for all projects you will create.

2022-09-22 14:04 UTC, Nyame-Wolf commented on index.html
> +</body>
Kindly note that this section has a [background image](https://stackoverflow.com/questions/492809/when-to-use-img-vs-css-background-image), according to the figma design.
<img width="182" alt="Screenshot 2022-09-22 at 16 50 13" src="https://user-images.githubusercontent.com/48546992/191765646-692acd61-d54c-4c66-ab17-91225bcb7ff0.png">
It results in the above pointed shapes.

2022-09-22 14:04 UTC, Nyame-Wolf commented on index.html
> +    <h1>I'm Saba<br> Glad to see<br> you!</h1>
Kindly note that for the text `Glad to see` and `you` should use a header tag that is  hx `<h1>,<h2>,<h3>`
This is to conform to the semantic correct way  and the screen readers and other technologies will thank you.

2022-09-22 14:04 UTC, Nyame-Wolf commented on style.css
> +  font-weight: 700;
Great job on getting your project to resemble the figma design. however, this project requires that you follow the figma design's font, colors and also space between the elements
## currently this is your design
<img width="1595" alt="Screenshot 2022-09-22 at 16 58 00" src="https://user-images.githubusercontent.com/48546992/191767658-89f825b3-1a96-48c2-8645-6917e5a0d333.png">
ts as well as arrangement.

## this is the figma desidn required.
<img width="182" alt="Screenshot 2022-09-22 at 16 50 13" src="https://user-images.githubusercontent.com/48546992/191767998-2dc008b0-81bc-473b-b1f5-d701492f5c94.png">
 

- [ ] Kindly note that its a requirement that the design has the media images below to social media pages.

2022-09-23 06:43 UTC, christianbiring1 approved these changes
Hi @SabaAhmad786 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
# STATUS: APPROVED :tada: 
![APPROVED](https://user-images.githubusercontent.com/97100091/191905233-2f974cf8-12b8-4905-ad24-1a4a03e209aa.gif)

## Highlights
- [ ] Linter tests are all green
- [ ] Descriptive pull request title and summary
- [ ] You have implemented all the required changes as requested by the previous reviewer.
:rocket: Jeep rolling you're doing a great job :+1:  :mechanical_arm: 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-23 06:43 UTC, christianbiring1 commented on style.css
> +  background-image: url(pics/shapes.png);
[OPTIONAL]
- [ ] Kindly make sure this `image` is set as `background` only for the `first section` and not of the `body` as you can see on the Figma design.

2022-09-23 08:50 UTC, merged